version: '3'
services:
  web:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - "mysql"
    env_file: ./.envDocker
    environment:
      - DB_HOST=mysql
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_NAME=$MYSQL_DB
      - DB_PORT=3306
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file: ./.envDocker
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB