version: '3'
services:
  web:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - "mysql"
    env_file: ./.env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DB=$MYSQL_DB
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB