version: '3'
services:
  web:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - "mysql"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/